import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';


const Home : NextPage = () => {
  return (
    <>
      <Head>
        <title>وب سایت برگ زندگی پویا</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h2 className='text-gray-500 border border-indigo-600 p-5'>Hello Zhoal</h2>
      <Link href='./auto/register'>register</Link>
    </>
  )
}

export default Home;